export default {
  // theme
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  // popular
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'LOAD_POPULAR_FAIL',
  POPULAR_REFRESH_SUCCESS: 'LOAD_POPULAR_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  FLUSH_POPULAR_FAVORITE: 'FLUSH_POPULAR_FAVORITE',
  // trending
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
  FLUSH_TRENDING_FAVORITE: 'FLUSH_TRENDING_FAVORITE',
  // favorite
  FAVORITE_LOAD_DATA: 'FAVORITE_LOAD_DATA',
  FAVORITE_LOAD_SUCCESS: 'FAVORITE_LOAD_SUCCESS',
  FAVORITE_LOAD_FAIL: 'FAVORITE_LOAD_FAIL',
  // language
  LANGUAGE_LOAD_SUCCESS: 'LANGUAGE_LOAD_SUCCESS',
};
