export default {
  // theme
  THEME_CHANGE: 'THEME_CHANGE',
  THEME_INIT: 'THEME_INIT',
  // popular
  POPULAR_REFRESH: 'POPULAR_REFRESH',
  POPULAR_REFRESH_FAIL: 'LOAD_POPULAR_FAIL',
  POPULAR_REFRESH_SUCCESS: 'LOAD_POPULAR_SUCCESS',
  POPULAR_LOAD_MORE_SUCCESS: 'POPULAR_LOAD_MORE_SUCCESS',
  POPULAR_LOAD_MORE_FAIL: 'POPULAR_LOAD_MORE_FAIL',
  // trending
  TRENDING_REFRESH: 'TRENDING_REFRESH',
  TRENDING_REFRESH_FAIL: 'TRENDING_REFRESH_FAIL',
  TRENDING_REFRESH_SUCCESS: 'TRENDING_REFRESH_SUCCESS',
  TRENDING_LOAD_MORE_SUCCESS: 'TRENDING_LOAD_MORE_SUCCESS',
  TRENDING_LOAD_MORE_FAIL: 'TRENDING_LOAD_MORE_FAIL',
};
